# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Does money make happiness? # Change this to your book title.
author: Mees Herder, Bruno Schlötter, Yousri Nait Aicha, Daniel Penninkhof # Change this to your name (or your team/organization name).

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/meesuva/Visualitie  # Online location of your book (change this to your GitHub repository link)
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

path_to_docs: docs  # Path to the directory containing your book files (change this if your book is in a different directory)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  theme:
    name: sphinx_book_theme  # Explicitly declare theme (you're likely using this)
    search_bar_text: ""  # Empty search text
    search_bar_position: "none"  # Disable completely
    # Optional: Clean up sidebar further
    show_navbar_depth: 1
    show_toc_level: 1

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    # This is to work around the bug of no syntax highlighting
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    master_doc: "1introduction"
    html_js_files:
      # This is for plotly to work
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js


